version: '3'
services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3059:3059"
    volumes:
      - ./data:/app/data
    restart: always
